### PR TITLE
Moved _set_output_format into function body

### PR DESCRIPTION
**Pull request by victorkemp**
so it compiles in Mingw on Windows.

### CODE REVIEW

**Comment by 3rav** [comment]
`_set_output_format` this function causes an error in the UCRT64 environment:

https://github.com/msys2/MINGW-packages/issues/15607#issue-1579990450

possible solution:

```
#ifdef __MSVC
_set_output_format(_TWO_DIGIT_EXPONENT);
#endif
```

`_set_output_format` is it needed at all since "This function is obsolete. Beginning in Visual Studio 2015, it is not available in the CRT."?

**Comment by lazka** [comment]
Maybe `#if defined(_WIN32) && !defined(_UCRT)` ?

**Comment by victorkemp** [comment]
I hope it can be removed entirely. It's just a bodge to fix an old bug in a MS library. There's also an environment variable that does that anyway.

**Comment by 3rav** [comment]
I confirm `#if defined(_WIN32) && !defined(_UCRT)` it works correctly

**Pull request closed without merging**
